import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

const title = "Server komponenter | Next.js";

export const metadata: Metadata = {
	title,
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased py-24`}
			>
				<main className="max-w-[650px] m-auto">
					<h1 className="text-4xl mb-6">{title}</h1>
					{children}
				</main>
			</body>
		</html>
	);
}
